<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CPC-ShaikIrF-B1" failures="2" tests="2" name="Employment_scenarios(failed)(failed)" time="61.106" errors="0" timestamp="2023-04-05T23:02:35 IST">
  <testcase classname="com.test.user.Employment_scenarios" name="RUNALL" time="29.181">
    <failure type="java.lang.Exception" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at com.pages.Employment.Validate_details_of_Hiit_Coach_position(Employment.java:781)
	at com.test.user.Employment_scenarios.RUNALL(Employment_scenarios.java:296)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
">
      <![CDATA[java.lang.Exception: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at com.pages.Employment.Validate_details_of_Hiit_Coach_position(Employment.java:781)
at com.test.user.Employment_scenarios.RUNALL(Employment_scenarios.java:296)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

at com.test.user.Employment_scenarios.RUNALL(Employment_scenarios.java:3085)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 50 stack frames]]>
    </failure>
  </testcase> <!-- RUNALL -->
  <testcase classname="com.test.user.Employment_scenarios" name="RUNALL" time="29.684">
    <failure type="java.lang.Exception" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at com.pages.Employment.Validate_details_of_Hiit_Coach_position(Employment.java:781)
	at com.pages.Employment.Validate_moreinfo_popupwindow_of_HCP(Employment.java:878)
	at com.test.user.Employment_scenarios.RUNALL(Employment_scenarios.java:325)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
">
      <![CDATA[java.lang.Exception: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at com.pages.Employment.Validate_details_of_Hiit_Coach_position(Employment.java:781)
at com.pages.Employment.Validate_moreinfo_popupwindow_of_HCP(Employment.java:878)
at com.test.user.Employment_scenarios.RUNALL(Employment_scenarios.java:325)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

at com.test.user.Employment_scenarios.RUNALL(Employment_scenarios.java:3085)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 50 stack frames]]>
    </failure>
  </testcase> <!-- RUNALL -->
</testsuite> <!-- Employment_scenarios(failed)(failed) -->
